### ISSUE TITLE
DotNET Issue [png]

### ISSUE THREAD

**Issue by Glatrix** [nifanfa/MOOS#27]
Getting this error when trying to run the virtual studio emulation.
![image](https://user-images.githubusercontent.com/73367967/167138734-ab626efa-36d1-44da-a3a3-5b8a579b6004.png)

**Comment by nifanfa** [comment]
Hello! you should install VMWare Player

**Comment by nifanfa** [comment]
https://www.vmware.com/products/workstation-player.html

**Comment by nifanfa** [comment]
https://github.com/nifanfa/MOOS/commit/b001f8ec2f022ac59d850a2009763c3b29d62ca1

**Comment by nifanfa** [comment]
join our discord server to get reply earlier. the link is on readme.md
