### ISSUE TITLE
Bare metal Freeze/Crash at Native.Sti() call in ThreadPool.Initialize

### ISSUE THREAD

**Issue by iBeizsley** [nifanfa/MOOS#71]
Running on an I7 6700K bare metal, OS freezes/crashes without any output at `Native.Sti()` call in `ThreadPool.Initialize()`

https://github.com/nifanfa/MOOS/blob/10737deb70ce82fe731a3debad1de298df8e47b1/Kernel/Misc/Threading.cs#L145

Same ISO works fine in QEMU, Can try to extract more information with WriteLines prior if it'd be at all helpful 😅 

Console.WriteLine before and after the call in question, output looks like:

![IMG_20221210_015439008.jpg](https://user-images.githubusercontent.com/23095702/206823129-84ceaa65-0d98-4687-a91e-89381de37ab4.jpg)

Happens with GC & GUI disabled, or enabled. Both work in VM. APIC build var can't be disabled without code changes; Timer and presumably other stuff uses it without compiler ifs.

**Comment by iBeizsley** [comment]
Same issue on i7 x230

![IMG_20221210_020257684.jpg](https://user-images.githubusercontent.com/23095702/206823410-78f3cd57-2f71-4c1a-bb87-98fdbfe549d9.jpg)

**Comment by nifanfa** [comment]
Does it just freeze or get panic information?

**Comment by nifanfa** [comment]
Oh @iBeizsley

**Comment by nifanfa** [comment]
Try not initialize sata controller

**Comment by nifanfa** [comment]
https://github.com/nifanfa/MOOS/blob/10737deb70ce82fe731a3debad1de298df8e47b1/Kernel/Misc/EntryPoint.cs#L79

**Comment by nifanfa** [comment]
i remember sata controller have some problems

**Comment by iBeizsley** [comment]
Just freezes, no panic. Disabling SATA didn't work, went ahead and tried with Keyboard, Serial, PS2, VMware tools, SMBIOS, PCI, IDE and SATA all disabled, same result:

![IMG_20221213_033539627.jpg](https://user-images.githubusercontent.com/23095702/207220672-014aa4ee-192a-420e-86f3-79a744c69736.jpg)

**Comment by nifanfa** [comment]
try not initialize threadpool and smp and see if it works

**Comment by nifanfa** [comment]
i'll check it as soon as possible

**Comment by nifanfa** [comment]
just make sure it is a problem of threadpool

**Comment by nifanfa** [comment]
![20221214_104333_HDR](https://user-images.githubusercontent.com/54205437/207492563-abc9a8fe-ec43-477d-b503-c92aad5bf5e0.jpg)

**Comment by nifanfa** [comment]
yeah i got the same problem

**Comment by nifanfa** [comment]
so the problem looks like the trampoline address

**Comment by nifanfa** [comment]
@iBeizsley

**Comment by nifanfa** [comment]
no the problem is ThreadPool for sure

**Comment by nifanfa** [comment]
https://github.com/nifanfa/MOOS/tree/stable
I just reverted the newest changes. you can use this one

**Comment by nifanfa** [comment]
it works fine on real hardware

**Comment by nifanfa** [comment]
![20221214_202157](https://user-images.githubusercontent.com/54205437/207594546-15c5a0e9-c5c4-48d2-833b-2b0572e51b34.jpg)

**Comment by nifanfa** [comment]
The problem might be with native aot itself. We can't make Corlib a lib instead of shared project

**Comment by nifanfa** [comment]
i just renamed the branch

**Comment by nifanfa** [comment]
So the problem is solved

**Comment by nifanfa** [comment]
i just renamed stable to main btw

**Comment by nifanfa** [comment]
let me know if it works now

**Comment by nifanfa** [comment]
I found that the real problem is that ILCompiler is not stable
