### ISSUE TITLE
有没有可能把 ReactOS的 兼容windows驱动的逻辑搬过来.

### ISSUE THREAD

**Issue by sgf** [nifanfa/MOOS#78]
有没有可能把 ReactOS的 兼容windows驱动的逻辑搬过来.

主要是为了后续或许可以 做大事.

当然,搬linux的话当然也可以 😂

**Comment by nifanfa** [comment]
移植的前提是你能实现他们驱动调用的内核函数。但是问题是你都能实现他们的内核函数你为啥不直接用他们的系统😒

**Comment by sgf** [comment]
> 移植的前提是你能实现他们驱动调用的内核函数。但是问题是你都能实现他们的内核函数你为啥不直接用他们的系统😒

他们系统能放到路由器里面吗?就算是俄罗斯给系统瘦身的大佬出手也不行吧?
我是感觉一个新系统,如果要做桌面的话怕是很难了.但是如果只是 做路由器系统,或者只是做云服务器的OS的话相对来说要求就很低了.

**Comment by nifanfa** [comment]
ReactOS不太行啊，你没试过吗。我之前玩过，莫名其妙蓝屏。反正不稳定，我感觉比我这个都不稳定

**Comment by nifanfa** [comment]
linux驱动没多大的。一个网卡驱动就几、几十kb

**Comment by sgf** [comment]
> ReactOS不太行啊，你没试过吗。我之前玩过，莫名其妙蓝屏。反正不稳定，我感觉比我这个都不稳定

没试过,关注过,我知道不太稳定.


> linux驱动没多大的。一个网卡驱动就几、几十kb

那你的意思是,后面可能实现linux的网卡驱动?但是网卡驱动不是可插拔的么?一个驱动几十kb,但是不同品牌不同型号的话....

**Comment by nifanfa** [comment]
> > ReactOS不太行啊，你没试过吗。我之前玩过，莫名其妙蓝屏。反正不稳定，我感觉比我这个都不稳定
> 
> 没试过,关注过,我知道不太稳定.但是我们又不需要整个ReactOS,只是需要驱动加载,运行那块的逻辑
> 
> > linux驱动没多大的。一个网卡驱动就几、几十kb
> 
> 那你的意思是,后面可能实现集成 linux的网卡驱动的逻辑?但是网卡驱动不是可插拔的么?一个驱动几十kb,但是不同品牌不同型号的话....

网卡一般是一个系列的。比如说intel 825xx系列网卡也就是e1000驱动是一样的。不过移植还是算了。工作量很大

**Comment by sgf** [comment]
> 网卡一般是一个系列的。比如说intel 825xx系列网卡也就是e1000驱动是一样的。不过移植还是算了。工作量很大

倒不是移植网卡驱动,只是实现wdk,ddk,sdk api之类的玩意儿. 
那么大佬,对于这个os,往实用化方向发展的话有什么计划不.

我感觉实用化的最大的两个方向:
1.向windows靠拢(难度大,但也不是不行,比如现在普遍存在的在安卓和IOS上面跑windows游戏的工具). 
2.向linux靠拢(难度也不小)
3.走出自己的路子

第3条,走自己的路子,这个不太可能.原因是:设备厂商不可能给你开发驱动.而没有设备支持,那基本上就没有什么实用性.
永远只能跑在假环境里面.


工作量这块,你只能考虑把这件事情交给社区,比如linus也不可能,所有事情亲历亲为. 
谁希望兼容或者支持什么功能,就让他们自己集成,你只需要把控系统最核心的一些东西.大框架,大方向.

**Comment by sgf** [comment]
另外:https://github.com/mosa/MOSA-Project 项目最近似乎又活跃了一瞬间. 然后又没有什么动静了.

**Comment by nifanfa** [comment]
没啥计划了。个人操作系统感觉注定没啥后文

**Comment by sgf** [comment]
行吧
